// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kidyme/nexus/control/internal"
	feedback2 "github.com/kidyme/nexus/control/internal/application/feedback"
	item2 "github.com/kidyme/nexus/control/internal/application/item"
	node2 "github.com/kidyme/nexus/control/internal/application/node"
	user2 "github.com/kidyme/nexus/control/internal/application/user"
	"github.com/kidyme/nexus/control/internal/infrastructure/feedback"
	"github.com/kidyme/nexus/control/internal/infrastructure/item"
	"github.com/kidyme/nexus/control/internal/infrastructure/node"
	refreshmeta "github.com/kidyme/nexus/control/internal/infrastructure/refreshmeta"
	"github.com/kidyme/nexus/control/internal/infrastructure/user"
	"github.com/kidyme/nexus/control/internal/port/http"
)

// Injectors from wire.go:

// InitializeApp 创建完成依赖注入的 control 运行时。
func InitializeApp() (*control.App, func(), error) {
	config, err := control.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	commonHandler := httpport.NewCommonHandler()
	registry, cleanup, err := control.ProvideRegistry(config)
	if err != nil {
		return nil, nil, err
	}
	repository := node.NewRepository(registry)
	service := node2.NewService(repository)
	nodeHandler := httpport.NewNodeHandler(service)
	db, cleanup2, err := control.ProvideMySQLDB(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, err := control.ProvideRedisClient(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	refreshMetaRepository := refreshmeta.NewRepository(client)
	userRepository := user.NewRepository(db)
	userService := user2.NewService(userRepository, refreshMetaRepository)
	userHandler := httpport.NewUserHandler(userService)
	itemRepository := item.NewRepository(db)
	itemService := item2.NewService(itemRepository, refreshMetaRepository)
	itemHandler := httpport.NewItemHandler(itemService)
	feedbackRepository := feedback.NewRepository(db)
	feedbackService := feedback2.NewService(feedbackRepository, refreshMetaRepository)
	feedbackHandler := httpport.NewFeedbackHandler(feedbackService)
	handlers := httpport.Handlers{
		Common:   commonHandler,
		Node:     nodeHandler,
		User:     userHandler,
		Item:     itemHandler,
		Feedback: feedbackHandler,
	}
	engine := httpport.NewRouter(handlers)
	httpServer := control.ProvideHTTPServer(config, engine)
	registryNode, err := control.ProvideSelfNode(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	duration := control.ProvideHeartbeatInterval(config)
	app := control.NewApp(httpServer, registry, registryNode, duration)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
