// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kidyme/nexus/control/internal/control"
	node2 "github.com/kidyme/nexus/control/internal/control/application/node"
	"github.com/kidyme/nexus/control/internal/control/infrastructure/node"
	"github.com/kidyme/nexus/control/internal/control/port/http"
)

// Injectors from wire.go:

// InitializeApp creates the fully wired control runtime.
func InitializeApp() (*control.App, func(), error) {
	config, err := control.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	commonHandler := httpport.NewCommonHandler()
	registry, cleanup, err := control.ProvideRegistry(config)
	if err != nil {
		return nil, nil, err
	}
	repository := node.NewRepository(registry)
	service := node2.NewService(repository)
	nodeHandler := httpport.NewNodeHandler(service)
	handlers := httpport.Handlers{
		Common: commonHandler,
		Node:   nodeHandler,
	}
	engine := httpport.NewRouter(handlers)
	httpServer := control.ProvideHTTPServer(config, engine)
	registryNode, err := control.ProvideSelfNode(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	duration := control.ProvideHeartbeatInterval(config)
	app := control.NewApp(httpServer, registry, registryNode, duration)
	return app, func() {
		cleanup()
	}, nil
}
