CREATE TABLE IF NOT EXISTS feedback (
  feedback_type VARCHAR(64) NOT NULL,
  user_id VARCHAR(191) NOT NULL,
  item_id VARCHAR(191) NOT NULL,
  value DOUBLE NOT NULL DEFAULT 0,
  timestamp TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (feedback_type, user_id, item_id)
);
