CREATE TABLE IF NOT EXISTS items (
  item_id VARCHAR(191) NOT NULL PRIMARY KEY,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  categories JSON NULL,
  timestamp TIMESTAMP NOT NULL,
  labels JSON NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
