CREATE TABLE IF NOT EXISTS users (
  user_id VARCHAR(191) NOT NULL PRIMARY KEY,
  labels JSON NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
